NumPy

https://numpy.org/


Getting started — pandas 1.4.1 documentation

https://pandas.pydata.org/docs/getting_started/index.html


GitHub - numpy/numpy: The fundamental package for scientific computing with Python.

https://github.com/numpy/numpy


GitHub - pandas-dev/pandas: Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more

https://github.com/pandas-dev/pandas


El array.ipynb - Google Drive

https://drive.google.com/file/d/1TAArP7SwUo6jnk65pWRgBIP0GoJ-k9q2/view?usp=sharing


Indexing on ndarrays — NumPy v1.22 Manual

https://numpy.org/doc/stable/user/basics.indexing.html


NumPy: the absolute basics for beginners — NumPy v1.22 Manual

https://numpy.org/doc/stable/user/absolute_beginners.html#what-is-an-array


El array.ipynb - Google Drive

https://drive.google.com/file/d/1TAArP7SwUo6jnk65pWRgBIP0GoJ-k9q2/view?usp=sharing

NUMPY

In [ ]:
import numpy as np

In [ ]:
#lista
lista=[1,2,3,6,5,8,9]
#covertir a un array
np.array(lista)

array([1, 2, 3, 6, 5, 8, 9])

In [ ]:
type(lista)

list

In [ ]:
matriz=[[1,2,3],[1,4,5]]
matriz=np.array(matriz)

In [ ]:
lista[1]

2

In [ ]:
lista[0]+lista[5]

9

In [ ]:
matriz

array([[1, 2, 3],
       [1, 4, 5]])

In [ ]:
matriz[0][2]

3

In [ ]:
lista[0:3]

[1, 2, 3]

In [ ]:
#desde la posicion 0
lista[:3]

[1, 2, 3]

In [ ]:
#todos los valores de las posiciones de 3 en 3
lista[::3]

[1, 6, 9]

In [ ]:
lista[-3:]

[5, 8, 9]

In [ ]:
#pone la matriz a nivel de filas, luego con despues de (,)
#a nivel de columnas
matriz[1:,0:2]

array([[1, 4]])

TIPOS DE DATOS

In [ ]:
arr=np.array([1,2,3,6,9,8])
arr.dtype

dtype('int64')

In [ ]:
#para trabaja con redes neuronales
#datos decimales
arr=np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('float64')

In [ ]:
arr=np.array([0,1,2,3,4,5])
arr=arr.astype(np.float64)
arr

array([0., 1., 2., 3., 4., 5.])

In [ ]:
arr=np.array([0,1,2,3,4,5])
arr=arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True,  True])

In [ ]:
arr=np.array([0,1,2,3,4,5])
arr=arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4', b'5'], dtype='|S21')

DIMENSIONES

In [ ]:
#dentro de una estructura
#estructura escalar
#estructura de una dimension
#estructura matricial
escalar=np.array(42)
print(escalar)
escalar.ndim

42


0

In [ ]:
vector=np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [ ]:
matriz=np.array([[[1,2,3],[1,5,89],[1,5,89]]])
print(matriz)
matriz.ndim

[[[ 1  2  3]
  [ 1  5 89]
  [ 1  5 89]]]


3

In [ ]:
tensor=np.array([[[1,2,3],[1,5,89]],[[1,2,3],[1,5,89]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 1  5 89]]

 [[ 1  2  3]
  [ 1  5 89]]]


3

In [ ]:
#variar las dimensiones
vector=np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [ ]:
expand=np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [ ]:
print(vector,vector.ndim)
#adecua la dimension de la matriz
vector_2=np.squeeze(vector)
print(vector_2,vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


CREANDO ARRAYS

Lecturas recomendadas

Array creation routines — NumPy v1.22 Manual

https://numpy.org/doc/stable/reference/routines.array-creation.html

In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#construye una estructura previa
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,10)#inicio, final, numero datos a generar

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand()#valores entre cero y uno

0.011206203672740611

In [ ]:
np.random.rand(4)

array([0.12753758, 0.74123269, 0.16681316, 0.08052734])

In [ ]:
np.random.rand(4,4)

array([[0.87730082, 0.58645091, 0.44190147, 0.77569965],
       [0.82025952, 0.83030884, 0.89387446, 0.5355252 ],
       [0.16890015, 0.25018487, 0.27365626, 0.88710464],
       [0.10704986, 0.3932594 , 0.49440321, 0.65533132]])

In [ ]:
np.random.randint(1,15)

1

In [ ]:
np.random.randint(1,100,(10,10))#definir una estructura de 10x10 de 100 elementos


array([[23, 21, 94, 85, 79,  9,  9, 85, 50, 44],
       [93, 85, 67, 37, 42, 79, 25, 17, 84, 99],
       [35, 59, 44, 79, 90, 68, 92, 81, 37, 86],
       [37, 20, 23, 24, 61, 36, 82, 71,  2, 70],
       [17, 36, 97, 29, 50, 76, 44,  6, 96, 39],
       [37, 29, 81, 27,  9, 84,  1, 69, 49, 23],
       [75, 68, 28, 78, 56, 71, 89, 82,  9, 41],
       [31, 48, 52, 45, 26, 24, 89, 27, 24, 94],
       [97, 10,  9, 19, 57, 29, 29, 47, 35,  1],
       [16, 16, 92, 32, 24, 37, 32,  8,  1, 23]])

SHAPE Y RESHAPE

In [ ]:
#shape: forma de un arreglo
#reshape:

In [ ]:
array=np.random.randint(1,10,(3,2))

In [ ]:
#las dimensiones de la matriz
array.shape

(3, 2)

In [ ]:
array

array([[1, 6],
       [5, 1],
       [7, 1]])

In [ ]:
array.reshape(1,6)

array([[1, 6, 5, 1, 7, 1]])

In [ ]:
array.reshape(2,3)

array([[1, 6, 5],
       [1, 7, 1]])

In [ ]:
np.reshape(array,(1,6))

array([[1, 6, 5, 1, 7, 1]])

In [ ]:
np.reshape(array,(2,3),'C')#en C

array([[1, 6, 5],
       [1, 7, 1]])

In [ ]:
np.reshape(array,(2,3),'F')#foltran

array([[1, 7, 1],
       [5, 6, 1]])

In [ ]:
np.reshape(array,(2,3),'A')#como la forma del guardado en memoria
#como mejor este optimizado en un sistema

array([[1, 6, 5],
       [1, 7, 1]])


Statistics — NumPy v1.22 Manual

https://numpy.org/doc/stable/reference/routines.statistics.html


Mathematical functions — NumPy v1.22 Manual

https://numpy.org/doc/stable/reference/routines.math.html


funciones_principales_numpy.ipynb - Google Drive

https://drive.google.com/file/d/1NyvVn9Q4f39lOzLVLLrsibK5hATmmgDM/view?usp=sharing

In [ ]:
arr=np.random.randint(1,20,10)

In [ ]:
matriz=arr.reshape(2,5)
matriz

array([[ 3, 12,  6, 16,  3],
       [ 4, 19,  9, 11,  8]])

In [ ]:
arr.max()

19

In [ ]:
matriz.max()

19

In [ ]:
#saca el maximo  del eje por columna de la matriz
matriz.max(0)

array([ 4, 19,  9, 16,  8])

In [ ]:
#por filas
matriz.max(1)

array([16, 19])

In [ ]:
#buscar el mayor, y dedevuelve su indice
arr.argmax()

6

In [ ]:
#evalua por columnas de cada una de las filas
#1 cuando es mayor, 0 cuando es menor
matriz.argmax(0)

array([1, 1, 1, 0, 1])

In [ ]:
arr.min()

3

In [ ]:
matriz.min(0)

array([ 3, 12,  6, 11,  3])

In [ ]:
arr.argmin()

0

In [ ]:
matriz.argmin()

0

In [ ]:
#devuelve la diferencia de pico mas alto y el menor
arr.ptp()

16

In [ ]:
matriz.ptp(0)

array([1, 7, 3, 5, 5])

In [ ]:
#valor que se encuentra en la mitad
np.percentile(arr,50)

8.5

In [ ]:
#el valor mas bajo
np.percentile(arr,0)

3.0

In [ ]:
#el percentil mas alto
np.percentile(arr,100)

19.0

In [ ]:
#ordena los valores del vector
arr.sort()
arr

array([ 3,  3,  4,  6,  8,  9, 11, 12, 16, 19])

In [ ]:
#entrega la mediana de un arreglo
np.median(arr)

8.5

In [ ]:
np.median(matriz,1)

array([ 4., 12.])

In [ ]:
#calculo de la desviacion estandar
np.std(arr)

5.18555686498567

In [ ]:
#calculo de la varianza
np.var(arr)

26.890000000000004

In [ ]:
#calculo del ala media, suma de valores entre el total
np.mean(arr)

9.1

In [ ]:
#concatenar
a=np.array([[1,2],[3,4]])
b=np.array([4,6])

In [ ]:
#expand, permite aumentar un 1 corchetes, esto permitira una correcta concatenacion
b=np.expand_dims(b,axis=0)
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [4, 6]])

In [ ]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 4],
       [3, 4, 6]])

COPY


numpy.copy — NumPy v1.22 Manual

https://numpy.org/doc/stable/reference/generated/numpy.copy.html


COPY.ipynb - Google Drive

https://drive.google.com/file/d/1s0XqssWmmE9fy_y4dI28QXKaMdYWGwo7/view?usp=sharing

OJO EL COPY  te servira para hacer alguna modificacion en arreglos y matrices

In [ ]:
arr1=np.arange(0,11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
trozo=arr1[0:6]

In [ ]:
trozo[:]=0

In [ ]:
arr_c=arr.copy()
arr_c

array([ 3,  3,  4,  6,  8,  9, 11, 12, 16, 19])

In [ ]:
#correcto al hacer el copy
arr_c[:]=100
arr_c

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
#error
arr1

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

CONDICIONES

In [ ]:
#inicio, stop, cantidad
arr=np.linspace(1,10,10,dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [ ]:
indices_cond=arr>5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
arr[arr>5]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [ ]:
arr[(arr>5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [ ]:
arr[arr>5]=99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

OPERACIONES

NumPy: the absolute basics for beginners — NumPy v1.22 Manual

https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations

In [ ]:
lista=[1,2]
lista

[1, 2]

In [ ]:
lista*2

[1, 2, 1, 2]

In [ ]:
arr=np.arange(0,10)
arr2=arr.copy()

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
1/arr

<ipython-input-325-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr**2


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr+arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
matriz=arr.reshape(2,5)
matriz2=matriz.copy()

In [ ]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
matriz+matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [ ]:
matriz-matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
#producto punto de matrices
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [ ]:
#operacion de producto punto
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

In [ ]:
arr=np.array([11,11,11,12,13,13,13,15,15,17,17,12,13,11,14,13,])
arr

array([11, 11, 11, 12, 13, 13, 13, 15, 15, 17, 17, 12, 13, 11, 14, 13])

In [ ]:
#devuelve los valores unicos del array
unique=np.unique(arr)
unique

array([11, 12, 13, 14, 15, 17])

In [ ]:
unique,ocurrence=np.unique(arr,return_counts=True)
print(unique)
ocurrence

[11 12 13 14 15 17]


array([4, 2, 5, 1, 2, 2])

QUIZ

In [ ]:
np.array([[1,2,3],[4,5,6],[7,8,9]]).ndim

2

Series y DataFrames en Pandas

In [ ]:
#array unidimensional: series
#estructura matricial, tamaño variable: dataframe
import pandas as pd

In [ ]:
#series
psg=pd.Series(['Navas','cavani','Neymar','paolo'],
          index=[1,7,10,30])

In [ ]:
pd.Series(['Navas','cavani','Neymar','paolo'])

0     Navas
1    cavani
2    Neymar
3     paolo
dtype: object

In [ ]:
dict={1:'navas',7:'Cavani',10:'Neymar',30:'Messi'}
#maneja una estructura
pd.Series(dict)

1      navas
7     Cavani
10    Neymar
30     Messi
dtype: object

In [ ]:
psg[0:3]

1      Navas
7     cavani
10    Neymar
dtype: object

In [ ]:
import pandas as pd

In [ ]:
di={'jugador':['navs','Mbape','Neymar','Messi'],
 'altura':[150,160,189,140],
 'goles':[1,2,3,4]}

In [ ]:
hop=pd.DataFrame(di,index=[1,7,10,30])

In [ ]:
tweets = [tuple(x) for x in hop.values]
tweets

[('navs', 150, 1), ('Mbape', 160, 2), ('Neymar', 189, 3), ('Messi', 140, 4)]

In [ ]:
players=pd.DataFrame(di)

In [ ]:
players.columns

Index(['jugador', 'altura', 'goles'], dtype='object')

In [ ]:
#indice por filas
players.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
pd.DataFrame(di)

jugador  altura  goles
0    navs     150      1
1   Mbape     160      2
2  Neymar     189      3
3   Messi     140      4

LEER ARCHIVOS CSV Y JSON CON PANDAS

pandas.read_csv — pandas 1.4.1 documentation

https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html


pandas.read_json — pandas 1.4.1 documentation

https://pandas.pydata.org/docs/reference/api/pandas.read_json.html


Kaggle: Your Machine Learning and Data Science Community

https://kaggle.com


Kaggle: Your Machine Learning and Data Science Community

https://kaggle.com


bestsellers with categories.csv - Google Drive

https://drive.google.com/file/d/1Ur6qQZiS24n8KGcR-xkwOFj29BdBsFWc/view?usp=sharing


Cargando archivos y loc e iloc.ipynb - Google Drive

https://drive.google.com/file/d/1WnQuFLcw9vL3dZmm6dlVIoi0Q5IQXHk_/view?usp=sharing


HPCharactersDataRaw.json - Google Drive

https://drive.google.com/file/d/17K7gO_LqrJ33hw7HAPwRhkp8OTcG8xtP/view?usp=sharing

In [ ]:
#el valor header pone la fila asignada en la cabecera
#tiene los valores como: header=None,0,1,2...
df_books=pd.read_csv('/content/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv',sep=',',header=0)

In [ ]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
df_books.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

In [ ]:
#podemos modificar los nombres del dataframe
df_books=pd.read_csv('/content/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv',sep=',',header=0,names=['Nombre', 'Autor', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'])
df_books

Nombre  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                        Autor  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
pd.read_json('/content/HPCharactersDataRaw.json')

Name                                               Link  \
0              Mrs. Abbott  https://www.hp-lexicon.org/character/abbott-fa...   
1            Hannah Abbott  https://www.hp-lexicon.org/character/abbott-fa...   
2            Abel Treetops  https://www.hp-lexicon.org/character/abel-tree...   
3         Euan Abercrombie  https://www.hp-lexicon.org/character/abercromb...   
4     Aberforth Dumbledore  https://www.hp-lexicon.org/character/dumbledor...   
...                    ...                                                ...   
1935        Georgi Zdravko  https://www.hp-lexicon.org/character/georgi-zd...   
1936                Zograf       https://www.hp-lexicon.org/character/zograf/   
1937                 Zonko        https://www.hp-lexicon.org/character/zonko/   
1938     Valentina Vázquez  https://www.hp-lexicon.org/character/valentina...   
1939         Zygmunt Budge  https://www.hp-lexicon.org/character/zygmunt-b...   

                                                  Descr  Gender Species/Race  \
0     Mrs. Abbott was the mother of Hannah Abbott, a...  Female        Witch   
1     Hannah Abbott is a Hufflepuff student in Harry...  Female        Witch   
2     Abel Treetops was a wizard from Cincinnati who...    Male       Wizard   
3     Euan Abercrombie was a small boy with prominen...    Male       Wizard   
4     Aberforth Dumbledore was a tall, thin, grumpy-...    Male       Wizard   
...                                                 ...     ...          ...   
1935  Georgi Zdravko played Keeper for the Bulgarian...    Male       Wizard   
1936  Zograf played Keeper for the Bulgarian Nationa...     NaN       Wizard   
1937  Founder(?) of Zonko’s Joke Shop. Possibly a re...     NaN      Unknown   
1938  Valentina Vázquez was President of the Argenti...  Female        Witch   
1939  Zygmunt Budge is considered to be one of the m...    Male       Wizard   

            Blood                 School  \
0     Muggle-born                Unknown   
1      Half-blood  Hogwarts - Hufflepuff   
2         Unknown                Unknown   
3         Unknown  Hogwarts - Gryffindor   
4      Half-blood     Hogwarts - Student   
...           ...                    ...   
1935      Unknown                Unknown   
1936      Unknown                Unknown   
1937      Unknown                Unknown   
1938      Unknown                Unknown   
1939      Unknown     Hogwarts - Student   

                                         Profession  
0                                           Unknown  
1                    Landlady of the Leaky Cauldron  
2                                           Unknown  
3                                           Unknown  
4                                            Barman  
...                                             ...  
1935                      Quidditch player (Seeker)  
1936                      Quidditch player (Keeper)  
1937                                        Unknown  
1938  President of the Argentinian Council of Magic  
1939    Potions Master, Potioneer, Inventor, Author  

[1940 rows x 8 columns]

In [ ]:
#lectura llave valor
pd.read_json('/content/HPCharactersDataRaw.json',typ='Series')

0       {'Name': 'Mrs. Abbott', 'Link': 'https://www.h...
1       {'Name': 'Hannah Abbott', 'Link': 'https://www...
2       {'Name': 'Abel Treetops', 'Link': 'https://www...
3       {'Name': 'Euan Abercrombie', 'Link': 'https://...
4       {'Name': 'Aberforth Dumbledore', 'Link': 'http...
                              ...                        
1935    {'Name': 'Georgi Zdravko', 'Link': 'https://ww...
1936    {'Name': 'Zograf', 'Link': 'https://www.hp-lex...
1937    {'Name': 'Zonko', 'Link': 'https://www.hp-lexi...
1938    {'Name': 'Valentina Vázquez', 'Link': 'https:/...
1939    {'Name': 'Zygmunt Budge', 'Link': 'https://www...
Length: 1940, dtype: object

Filtrado con loc y iloc

In [ ]:
#indice 0 al 4
df_books[0:4]

Nombre               Autor  User Rating  \
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7   
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   
3                   1984 (Signet Classics)       George Orwell          4.7   

   Reviews  Price  Year        Genre  
0    17350      8  2016  Non Fiction  
1     2052     22  2011      Fiction  
2    18979     15  2018  Non Fiction  
3    21424      6  2017      Fiction

In [ ]:
#filtrando por el eje de las columnas
df_books['Nombre']

0                          10-Day Green Smoothie Cleanse
1                                      11/22/63: A Novel
2                12 Rules for Life: An Antidote to Chaos
3                                 1984 (Signet Classics)
4      5,000 Awesome Facts (About Everything!) (Natio...
                             ...                        
545         Wrecking Ball (Diary of a Wimpy Kid Book 14)
546    You Are a Badass: How to Stop Doubting Your Gr...
547    You Are a Badass: How to Stop Doubting Your Gr...
548    You Are a Badass: How to Stop Doubting Your Gr...
549    You Are a Badass: How to Stop Doubting Your Gr...
Name: Nombre, Length: 550, dtype: object

In [ ]:
df_books[['Nombre','Autor','User Rating']]

Nombre  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                        Autor  User Rating  
0                    JJ Smith          4.7  
1                Stephen King          4.6  
2          Jordan B. Peterson          4.7  
3               George Orwell          4.7  
4    National Geographic Kids          4.8  
..                        ...          ...  
545               Jeff Kinney          4.9  
546               Jen Sincero          4.7  
547               Jen Sincero          4.7  
548               Jen Sincero          4.7  
549               Jen Sincero          4.7  

[550 rows x 3 columns]

In [ ]:
#filtrar por alguna de las filas seleccionadas anteriormente
#Loc: esta basada en labels
df_books.loc[:]

Nombre  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                        Autor  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
df_books.loc[0:4,['Nombre','Autor']]

Nombre                     Autor
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

In [ ]:
df_books.loc[:,['Reviews']]

Reviews
0      17350
1       2052
2      18979
3      21424
4       7665
..       ...
545     9413
546    14331
547    14331
548    14331
549    14331

[550 rows x 1 columns]

In [ ]:
df_books.loc[:,['Reviews']]*-1

Reviews
0     -17350
1      -2052
2     -18979
3     -21424
4      -7665
..       ...
545    -9413
546   -14331
547   -14331
548   -14331
549   -14331

[550 rows x 1 columns]

In [ ]:
df_books.loc[:,['Autor']]=='JJ Smith'

Autor
0     True
1    False
2    False
3    False
4    False
..     ...
545  False
546  False
547  False
548  False
549  False

[550 rows x 1 columns]

In [ ]:
#busqueda por indices a nivel de columnas de 0 al 3
df_books.iloc[:,0:3]

Nombre  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                        Autor  User Rating  
0                    JJ Smith          4.7  
1                Stephen King          4.6  
2          Jordan B. Peterson          4.7  
3               George Orwell          4.7  
4    National Geographic Kids          4.8  
..                        ...          ...  
545               Jeff Kinney          4.9  
546               Jen Sincero          4.7  
547               Jen Sincero          4.7  
548               Jen Sincero          4.7  
549               Jen Sincero          4.7  

[550 rows x 3 columns]

In [ ]:
df_books.iloc[1,0:3]

Nombre         11/22/63: A Novel
Autor               Stephen King
User Rating                  4.6
Name: 1, dtype: object

In [ ]:
df_books.iloc[1,3]*-1

-2052

In [ ]:
#recupera las dos primeras filas y desde la tercer a columna
df_books.iloc[:2,2:]

User Rating  Reviews  Price  Year        Genre
0          4.7    17350      8  2016  Non Fiction
1          4.6     2052     22  2011      Fiction

Agregar o eliminar datos con Pandas

pandas.DataFrame.drop — pandas 1.4.1 documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html


pandas.DataFrame.append — pandas 1.4.1 documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.append.html


agregar_eliminar.ipynb - Google Drive

https://drive.google.com/file/d/1MOZlKSz1zQ7TmhN5c3rH5D1pBRvE1rG1/view?usp=sharing

In [ ]:
df_books.head()

Nombre  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                      Autor  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [ ]:
#eliminar las columnas
df_books.drop('Genre',axis=1).head()

Nombre  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                      Autor  User Rating  Reviews  Price  Year  
0                  JJ Smith          4.7    17350      8  2016  
1              Stephen King          4.6     2052     22  2011  
2        Jordan B. Peterson          4.7    18979     15  2018  
3             George Orwell          4.7    21424      6  2017  
4  National Geographic Kids          4.8     7665     12  2019

In [ ]:
df_books.head()

Nombre  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                      Autor  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [ ]:
#borra de la salida y no del dataframe

In [ ]:
df_books.drop('Genre',axis=1,inplace=True)

In [ ]:
df_books.head()

Nombre  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                      Autor  User Rating  Reviews  Price  Year  
0                  JJ Smith          4.7    17350      8  2016  
1              Stephen King          4.6     2052     22  2011  
2        Jordan B. Peterson          4.7    18979     15  2018  
3             George Orwell          4.7    21424      6  2017  
4  National Geographic Kids          4.8     7665     12  2019

In [ ]:
dfb=df_books.drop('Year',axis=1)

In [ ]:
dfb.head(2)

Nombre         Autor  User Rating  Reviews  Price
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8
1              11/22/63: A Novel  Stephen King          4.6     2052     22

In [ ]:
del df_books['Price']

In [ ]:
#borrar columas
df_books.drop(0,axis=0)

Nombre  \
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
5        A Dance with Dragons (A Song of Ice and Fire)   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                        Autor  User Rating  Reviews  Year  
1                Stephen King          4.6     2052  2011  
2          Jordan B. Peterson          4.7    18979  2018  
3               George Orwell          4.7    21424  2017  
4    National Geographic Kids          4.8     7665  2019  
5         George R. R. Martin          4.4    12643  2011  
..                        ...          ...      ...   ...  
545               Jeff Kinney          4.9     9413  2019  
546               Jen Sincero          4.7    14331  2016  
547               Jen Sincero          4.7    14331  2017  
548               Jen Sincero          4.7    14331  2018  
549               Jen Sincero          4.7    14331  2019  

[549 rows x 5 columns]

In [ ]:
#borrado de una lista
#elimina los 10 primeros datos
df_books.drop(range(0,10),axis=0).head(2)
#df_books.drop([0,1,2],axis=0).head(2)

Nombre             Autor  \
10                          A Man Called Ove: A Novel   Fredrik Backman   
11  A Patriot's History of the United States: From...  Larry Schweikart   

    User Rating  Reviews  Year  
10          4.6    23848  2017  
11          4.6      460  2010

In [ ]:
#agregar columnas
df_books.head(2)

Nombre         Autor  User Rating  Reviews  Year
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350  2016
1              11/22/63: A Novel  Stephen King          4.6     2052  2011

In [ ]:
df_books['nueva_columnas']=np.nan
df_books.head()

Nombre  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                      Autor  User Rating  Reviews  Year  nueva_columnas  
0                  JJ Smith          4.7    17350  2016             NaN  
1              Stephen King          4.6     2052  2011             NaN  
2        Jordan B. Peterson          4.7    18979  2018             NaN  
3             George Orwell          4.7    21424  2017             NaN  
4  National Geographic Kids          4.8     7665  2019             NaN

In [ ]:
#numero de registros
df_books.shape[0]

550

In [ ]:
data=np.arange(df_books.shape[0])
data

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
df_books['Rango']=data
df_books.head()

Nombre  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                      Autor  User Rating  Reviews  Year  nueva_columnas  Rango  
0                  JJ Smith          4.7    17350  2016             NaN      0  
1              Stephen King          4.6     2052  2011             NaN      1  
2        Jordan B. Peterson          4.7    18979  2018             NaN      2  
3             George Orwell          4.7    21424  2017             NaN      3  
4  National Geographic Kids          4.8     7665  2019             NaN      4

In [ ]:
df_books.append(df_books)

Nombre  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                        Autor  User Rating  Reviews  Year  nueva_columnas  \
0                    JJ Smith          4.7    17350  2016             NaN   
1                Stephen King          4.6     2052  2011             NaN   
2          Jordan B. Peterson          4.7    18979  2018             NaN   
3               George Orwell          4.7    21424  2017             NaN   
4    National Geographic Kids          4.8     7665  2019             NaN   
..                        ...          ...      ...   ...             ...   
545               Jeff Kinney          4.9     9413  2019             NaN   
546               Jen Sincero          4.7    14331  2016             NaN   
547               Jen Sincero          4.7    14331  2017             NaN   
548               Jen Sincero          4.7    14331  2018             NaN   
549               Jen Sincero          4.7    14331  2019             NaN   

     Rango  
0        0  
1        1  
2        2  
3        3  
4        4  
..     ...  
545    545  
546    546  
547    547  
548    548  
549    549  

[2200 rows x 7 columns]

In [ ]:
df_books = pd.concat([df_books, df_books])
df_books

Nombre  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                        Autor  User Rating  Reviews  Year  nueva_columnas  \
0                    JJ Smith          4.7    17350  2016             NaN   
1                Stephen King          4.6     2052  2011             NaN   
2          Jordan B. Peterson          4.7    18979  2018             NaN   
3               George Orwell          4.7    21424  2017             NaN   
4    National Geographic Kids          4.8     7665  2019             NaN   
..                        ...          ...      ...   ...             ...   
545               Jeff Kinney          4.9     9413  2019             NaN   
546               Jen Sincero          4.7    14331  2016             NaN   
547               Jen Sincero          4.7    14331  2017             NaN   
548               Jen Sincero          4.7    14331  2018             NaN   
549               Jen Sincero          4.7    14331  2019             NaN   

     Rango  
0        0  
1        1  
2        2  
3        3  
4        4  
..     ...  
545    545  
546    546  
547    547  
548    548  
549    549  

[1100 rows x 7 columns]

Manejo de datos nulos






pandas.isnull — pandas 1.4.1 documentation

https://pandas.pydata.org/docs/reference/api/pandas.isnull.html


pandas.DataFrame.fillna — pandas 1.4.1 documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html


pandas.DataFrame.dropna — pandas 1.4.1 documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html


Valores_nulos.ipynb - Google Drive

https://drive.google.com/file/d/1awJOBwVKrfY9z4F5m4LvSnuh9s4YwwLE/view?usp=s

In [ ]:
dict={'col':[1,2,3,np.nan],
 'col2':[4,np.nan,6,7],
 'col3':['a','b','c',None]}

In [ ]:
df=pd.DataFrame(dict)
df

col  col2  col3
0  1.0   4.0     a
1  2.0   NaN     b
2  3.0   6.0     c
3  NaN   7.0  None

In [ ]:
#verificar si es nulo
df.isnull()

col   col2   col3
0  False  False  False
1  False   True  False
2  False  False  False
3   True  False   True

In [ ]:
df.isnull()*1

col  col2  col3
0    0     0     0
1    0     1     0
2    0     0     0
3    1     0     1

In [ ]:
#cada vez que se identica los valores nulos
#se rellenan con un valor
df.fillna('Missing')

col     col2     col3
0      1.0      4.0        a
1      2.0  Missing        b
2      3.0      6.0        c
3  Missing      7.0  Missing

In [ ]:
df.fillna(df.mean())

<ipython-input-399-a2478f315f9e>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(df.mean())


col      col2  col3
0  1.0  4.000000     a
1  2.0  5.666667     b
2  3.0  6.000000     c
3  2.0  7.000000  None

In [ ]:
#asume un valor como una serie, en los valores nulos
df.interpolate()

col  col2  col3
0  1.0   4.0     a
1  2.0   5.0     b
2  3.0   6.0     c
3  3.0   7.0  None

In [ ]:
#borrar todas las filas con valores nulos
df.dropna()

col  col2 col3
0  1.0   4.0    a
2  3.0   6.0    c

FILTRANDO CONDICIONALES

In [ ]:
df_books.head(2)

Nombre         Autor  User Rating  Reviews  Year  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350  2016   
1              11/22/63: A Novel  Stephen King          4.6     2052  2011   

   nueva_columnas  Rango  
0             NaN      0  
1             NaN      1

In [ ]:
m2016=df_books['Year']>2016

In [ ]:
df_books[m2016]

Nombre  \
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
7                       A Gentleman in Moscow: A Novel   
8        A Higher Loyalty: Truth, Lies, and Leadership   
..                                                 ...   
544                                             Wonder   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                        Autor  User Rating  Reviews  Year  nueva_columnas  \
2          Jordan B. Peterson          4.7    18979  2018             NaN   
3               George Orwell          4.7    21424  2017             NaN   
4    National Geographic Kids          4.8     7665  2019             NaN   
7                 Amor Towles          4.7    19699  2017             NaN   
8                 James Comey          4.7     5983  2018             NaN   
..                        ...          ...      ...   ...             ...   
544             R. J. Palacio          4.8    21625  2017             NaN   
545               Jeff Kinney          4.9     9413  2019             NaN   
547               Jen Sincero          4.7    14331  2017             NaN   
548               Jen Sincero          4.7    14331  2018             NaN   
549               Jen Sincero          4.7    14331  2019             NaN   

     Rango  
2        2  
3        3  
4        4  
7        7  
8        8  
..     ...  
544    544  
545    545  
547    547  
548    548  
549    549  

[300 rows x 7 columns]

In [ ]:
genre_fiction=df_books['Autor']=='Jen Sincero'
genre_fiction

0      False
1      False
2      False
3      False
4      False
       ...  
545    False
546     True
547     True
548     True
549     True
Name: Autor, Length: 1100, dtype: bool

In [ ]:
df_books[genre_fiction & m2016]

Nombre        Autor  \
547  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
548  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
549  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
547  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
548  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
549  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   

     User Rating  Reviews  Year  nueva_columnas  Rango  
547          4.7    14331  2017             NaN    547  
548          4.7    14331  2018             NaN    548  
549          4.7    14331  2019             NaN    549  
547          4.7    14331  2017             NaN    547  
548          4.7    14331  2018             NaN    548  
549          4.7    14331  2019             NaN    549

In [ ]:
#datos menores o iguales a 2016
df_books[~m2016]

Nombre                Autor  \
0                        10-Day Green Smoothie Cleanse             JJ Smith   
1                                    11/22/63: A Novel         Stephen King   
5        A Dance with Dragons (A Song of Ice and Fire)  George R. R. Martin   
6    A Game of Thrones / A Clash of Kings / A Storm...  George R. R. Martin   
9                            A Man Called Ove: A Novel      Fredrik Backman   
..                                                 ...                  ...   
540                                             Wonder        R. J. Palacio   
541                                             Wonder        R. J. Palacio   
542                                             Wonder        R. J. Palacio   
543                                             Wonder        R. J. Palacio   
546  You Are a Badass: How to Stop Doubting Your Gr...          Jen Sincero   

     User Rating  Reviews  Year  nueva_columnas  Rango  
0            4.7    17350  2016             NaN      0  
1            4.6     2052  2011             NaN      1  
5            4.4    12643  2011             NaN      5  
6            4.7    19735  2014             NaN      6  
9            4.6    23848  2016             NaN      9  
..           ...      ...   ...             ...    ...  
540          4.8    21625  2013             NaN    540  
541          4.8    21625  2014             NaN    541  
542          4.8    21625  2015             NaN    542  
543          4.8    21625  2016             NaN    543  
546          4.7    14331  2016             NaN    546  

[800 rows x 7 columns]

Funciones principales de Pandas
[texto del enlace](https://)


10 minutes to pandas — pandas 1.4.1 documentation

https://pandas.pydata.org/docs/user_guide/10min.html

In [ ]:
df_books.head(2)

Nombre         Autor  User Rating  Reviews  Year  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350  2016   
1              11/22/63: A Novel  Stephen King          4.6     2052  2011   

   nueva_columnas  Rango  
0             NaN      0  
1             NaN      1

In [ ]:
df_books.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1100 entries, 0 to 549
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Nombre          1100 non-null   object 
 1   Autor           1100 non-null   object 
 2   User Rating     1100 non-null   float64
 3   Reviews         1100 non-null   int64  
 4   Year            1100 non-null   int64  
 5   nueva_columnas  0 non-null      float64
 6   Rango           1100 non-null   int64  
dtypes: float64(2), int64(3), object(2)
memory usage: 68.8+ KB


In [ ]:
#de las columnas numericas, me da sus datos estadisticos
df_books.describe()

User Rating       Reviews         Year  nueva_columnas       Rango
count  1100.000000   1100.000000  1100.000000             0.0  1100.00000
mean      4.618364  11953.281818  2014.000000             NaN   274.50000
std       0.226877  11725.793618     3.163716             NaN   158.84328
min       3.300000     37.000000  2009.000000             NaN     0.00000
25%       4.500000   4028.000000  2011.000000             NaN   137.00000
50%       4.700000   8580.000000  2014.000000             NaN   274.50000
75%       4.800000  17323.000000  2017.000000             NaN   412.00000
max       4.900000  87841.000000  2019.000000             NaN   549.00000

In [ ]:
#devuelve los ultimos dos registros
df_books.tail(2)

Nombre        Autor  \
548  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
549  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   

     User Rating  Reviews  Year  nueva_columnas  Rango  
548          4.7    14331  2018             NaN    548  
549          4.7    14331  2019             NaN    549

In [ ]:
#canta memoria se utiliza a nivel de columna
df_books.memory_usage(deep=True)

Index               8800
Nombre            119474
Autor              78156
User Rating         8800
Reviews             8800
Year                8800
nueva_columnas      8800
Rango               8800
dtype: int64

In [ ]:
#numero de autores por autor
df_books['Autor'].value_counts()

Jeff Kinney                           24
Gary Chapman                          22
Rick Riordan                          22
Suzanne Collins                       22
American Psychological Association    20
                                      ..
Keith Richards                         2
Chris Cleave                           2
Alice Schertle                         2
Celeste Ng                             2
Adam Gasiewski                         2
Name: Autor, Length: 248, dtype: int64

In [ ]:
df_books.iloc[0]

Nombre            10-Day Green Smoothie Cleanse
Autor                                  JJ Smith
User Rating                                 4.7
Reviews                                   17350
Year                                       2016
nueva_columnas                              NaN
Rango                                         0
Name: 0, dtype: object

In [ ]:
df_books=df_books.append(df_books.iloc[0])
df_books

Nombre  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
0                        10-Day Green Smoothie Cleanse   
0                        10-Day Green Smoothie Cleanse   

                        Autor  User Rating  Reviews  Year  nueva_columnas  \
0                    JJ Smith          4.7    17350  2016             NaN   
1                Stephen King          4.6     2052  2011             NaN   
2          Jordan B. Peterson          4.7    18979  2018             NaN   
3               George Orwell          4.7    21424  2017             NaN   
4    National Geographic Kids          4.8     7665  2019             NaN   
..                        ...          ...      ...   ...             ...   
547               Jen Sincero          4.7    14331  2017             NaN   
548               Jen Sincero          4.7    14331  2018             NaN   
549               Jen Sincero          4.7    14331  2019             NaN   
0                    JJ Smith          4.7    17350  2016             NaN   
0                    JJ Smith          4.7    17350  2016             NaN   

     Rango  
0        0  
1        1  
2        2  
3        3  
4        4  
..     ...  
547    547  
548    548  
549    549  
0        0  
0        0  

[1102 rows x 7 columns]

In [ ]:
#elimina los duplicados de los datos
df_books.drop_duplicates()
#No elimina el ultimo duplicado
#df_books.drop_duplicates(kee='last')

Nombre  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                        Autor  User Rating  Reviews  Year  nueva_columnas  \
0                    JJ Smith          4.7    17350  2016             NaN   
1                Stephen King          4.6     2052  2011             NaN   
2          Jordan B. Peterson          4.7    18979  2018             NaN   
3               George Orwell          4.7    21424  2017             NaN   
4    National Geographic Kids          4.8     7665  2019             NaN   
..                        ...          ...      ...   ...             ...   
545               Jeff Kinney          4.9     9413  2019             NaN   
546               Jen Sincero          4.7    14331  2016             NaN   
547               Jen Sincero          4.7    14331  2017             NaN   
548               Jen Sincero          4.7    14331  2018             NaN   
549               Jen Sincero          4.7    14331  2019             NaN   

     Rango  
0        0  
1        1  
2        2  
3        3  
4        4  
..     ...  
545    545  
546    546  
547    547  
548    548  
549    549  

[550 rows x 7 columns]

In [ ]:
df_books.sort_values('Year')

Nombre                Autor  \
364                       The Elegance of the Hedgehog       Muriel Barbery   
216      Liberty and Tyranny: A Conservative Manifesto        Mark R. Levin   
299                                  Sookie Stackhouse     Charlaine Harris   
304                                StrengthsFinder 2.0               Gallup   
313  Super Freakonomics: Global Cooling, Patriotic ...     Steven D. Levitt   
..                                                 ...                  ...   
252                          Oh, the Places You'll Go!            Dr. Seuss   
130  Girl, Wash Your Face: Stop Believing the Lies ...        Rachel Hollis   
240  National Geographic Little Kids First Big Book...          Amy Shields   
138  Good Days Start With Gratitude: A 52 Week Guid...  Pretty Simple Press   
128  Girl, Stop Apologizing: A Shame-Free Plan for ...        Rachel Hollis   

     User Rating  Reviews  Year  nueva_columnas  Rango  
364          4.0     1859  2009             NaN    364  
216          4.8     3828  2009             NaN    216  
299          4.7      973  2009             NaN    299  
304          4.0     5069  2009             NaN    304  
313          4.5     1583  2009             NaN    313  
..           ...      ...   ...             ...    ...  
252          4.9    21834  2019             NaN    252  
130          4.6    22288  2019             NaN    130  
240          4.8     7866  2019             NaN    240  
138          4.6    10141  2019             NaN    138  
128          4.6     7660  2019             NaN    128  

[1102 rows x 7 columns]

In [ ]:
#se ordenan los datos de forma descendente
df_books.sort_values('Year',ascending=False)

Nombre              Autor  \
184  Instant Pot Pressure Cooker Cookbook: 500 Ever...     Jennifer Smith   
179                       If Animals Kissed Good Night  Ann Whitford Paul   
33                                            Becoming     Michelle Obama   
491                                   The Wonky Donkey        Craig Smith   
176  I Am Confident, Brave & Beautiful: A Coloring ...    Hopscotch Girls   
..                                                 ...                ...   
50         Crazy Love: Overwhelmed by a Relentless God       Francis Chan   
260                     Outliers: The Story of Success   Malcolm Gladwell   
38           Breaking Dawn (The Twilight Saga, Book 4)    Stephenie Meyer   
417                                   The Last Lecture       Randy Pausch   
369  The Five Dysfunctions of a Team: A Leadership ...   Patrick Lencioni   

     User Rating  Reviews  Year  nueva_columnas  Rango  
184          4.4     7396  2019             NaN    184  
179          4.8    16643  2019             NaN    179  
33           4.8    61133  2019             NaN     33  
491          4.8    30183  2019             NaN    491  
176          4.8     9737  2019             NaN    176  
..           ...      ...   ...             ...    ...  
50           4.7     1542  2009             NaN     50  
260          4.6    10426  2009             NaN    260  
38           4.6     9769  2009             NaN     38  
417          4.7     4028  2009             NaN    417  
369          4.6     3207  2009             NaN    369  

[1102 rows x 7 columns]

groupby

In [ ]:
#te muestra el numero de registros por autor agupados
df_books.groupby('Autor').count()

Nombre  User Rating  Reviews  Year  \
Autor                                                            
Abraham Verghese                 4            4        4     4   
Adam Gasiewski                   2            2        2     2   
Adam Mansbach                    2            2        2     2   
Adir Levy                        2            2        2     2   
Admiral William H. McRaven       2            2        2     2   
...                            ...          ...      ...   ...   
Walter Isaacson                  6            6        6     6   
William Davis                    4            4        4     4   
William P. Young                 4            4        4     4   
Wizards RPG Team                 6            6        6     6   
Zhi Gang Sha                     4            4        4     4   

                            nueva_columnas  Rango  
Autor                                              
Abraham Verghese                         0      4  
Adam Gasiewski                           0      2  
Adam Mansbach                            0      2  
Adir Levy                                0      2  
Admiral William H. McRaven               0      2  
...                                    ...    ...  
Walter Isaacson                          0      6  
William Davis                            0      4  
William P. Young                         0      4  
Wizards RPG Team                         0      6  
Zhi Gang Sha                             0      4  

[248 rows x 6 columns]

In [ ]:
#min
#max
#mean
#sum
df_books.groupby('Autor').sum()

User Rating  Reviews   Year  nueva_columnas  Rango
Autor                                                                         
Abraham Verghese                   18.4    19464   8042             0.0    226
Adam Gasiewski                      8.8     6226   4034             0.0    464
Adam Mansbach                       9.6    19136   4022             0.0    266
Adir Levy                           9.6    16340   4038             0.0   1058
Admiral William H. McRaven          9.4    20398   4034             0.0    454
...                                 ...      ...    ...             ...    ...
Walter Isaacson                    27.4    37336  12080             0.0   1634
William Davis                      17.6    29988   8050             0.0   2126
William P. Young                   18.4    78880   8052             0.0   1838
Wizards RPG Team                   28.8   101940  12108             0.0   1596
Zhi Gang Sha                       18.4      514   8044             0.0    756

[248 rows x 5 columns]

In [ ]:
df_books.groupby('Autor').sum().loc['William Davis']

User Rating          17.6
Reviews           29988.0
Year               8050.0
nueva_columnas        0.0
Rango              2126.0
Name: William Davis, dtype: float64

In [ ]:
#autor vuelve a ser parte de nombre de laas columnas
df_books.groupby('Autor').sum().reset_index()

Autor  User Rating  Reviews   Year  nueva_columnas  \
0              Abraham Verghese         18.4    19464   8042             0.0   
1                Adam Gasiewski          8.8     6226   4034             0.0   
2                 Adam Mansbach          9.6    19136   4022             0.0   
3                     Adir Levy          9.6    16340   4038             0.0   
4    Admiral William H. McRaven          9.4    20398   4034             0.0   
..                          ...          ...      ...    ...             ...   
243             Walter Isaacson         27.4    37336  12080             0.0   
244               William Davis         17.6    29988   8050             0.0   
245            William P. Young         18.4    78880   8052             0.0   
246            Wizards RPG Team         28.8   101940  12108             0.0   
247                Zhi Gang Sha         18.4      514   8044             0.0   

     Rango  
0      226  
1      464  
2      266  
3     1058  
4      454  
..     ...  
243   1634  
244   2126  
245   1838  
246   1596  
247    756  

[248 rows x 6 columns]

In [ ]:
# te saca el minimo y maximo
df_books.groupby('Autor').sum()

User Rating  Reviews   Year  nueva_columnas  Rango
Autor                                                                         
Abraham Verghese                   18.4    19464   8042             0.0    226
Adam Gasiewski                      8.8     6226   4034             0.0    464
Adam Mansbach                       9.6    19136   4022             0.0    266
Adir Levy                           9.6    16340   4038             0.0   1058
Admiral William H. McRaven          9.4    20398   4034             0.0    454
...                                 ...      ...    ...             ...    ...
Walter Isaacson                    27.4    37336  12080             0.0   1634
William Davis                      17.6    29988   8050             0.0   2126
William P. Young                   18.4    78880   8052             0.0   1838
Wizards RPG Team                   28.8   101940  12108             0.0   1596
Zhi Gang Sha                       18.4      514   8044             0.0    756

[248 rows x 5 columns]

In [ ]:
df_books.groupby('Autor').agg({'Reviews': ['min','max'],'User Rating':'sum'})

Reviews        User Rating
                               min    max         sum
Autor                                                
Abraham Verghese              4866   4866        18.4
Adam Gasiewski                3113   3113         8.8
Adam Mansbach                 9568   9568         9.6
Adir Levy                     8170   8170         9.6
Admiral William H. McRaven   10199  10199         9.4
...                            ...    ...         ...
Walter Isaacson               3014   7827        27.4
William Davis                 7497   7497        17.6
William P. Young             19720  19720        18.4
Wizards RPG Team             16990  16990        28.8
Zhi Gang Sha                    37    220        18.4

[248 rows x 3 columns]

In [ ]:
df_books.groupby('Autor').agg({'Year':lambda x: [i-2000 for i in x], 'Reviews':lambda x: sum([i**2 for i in x])})

Year     Reviews
Autor                                                           
Abraham Verghese                    [10, 11, 10, 11]    94711824
Adam Gasiewski                              [17, 17]    19381538
Adam Mansbach                               [11, 11]   183093248
Adir Levy                                   [19, 19]   133497800
Admiral William H. McRaven                  [17, 17]   208039202
...                                              ...         ...
Walter Isaacson             [17, 11, 12, 17, 11, 12]   263216108
William Davis                       [12, 13, 12, 13]   224820036
William P. Young                      [9, 17, 9, 17]  1555513600
Wizards RPG Team            [17, 18, 19, 17, 18, 19]  1731960600
Zhi Gang Sha                          [9, 13, 9, 13]       99538

[248 rows x 2 columns]

In [ ]:
df_books.groupby(['Autor','Year']).count()

Nombre  User Rating  Reviews  nueva_columnas  Rango
Autor            Year                                                     
Abraham Verghese 2010       2            2        2               0      2
                 2011       2            2        2               0      2
Adam Gasiewski   2017       2            2        2               0      2
Adam Mansbach    2011       2            2        2               0      2
Adir Levy        2019       2            2        2               0      2
...                       ...          ...      ...             ...    ...
Wizards RPG Team 2017       2            2        2               0      2
                 2018       2            2        2               0      2
                 2019       2            2        2               0      2
Zhi Gang Sha     2009       2            2        2               0      2
                 2013       2            2        2               0      2

[493 rows x 5 columns]


pandas.DataFrame.groupby — pandas 1.4.1 documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html

Combinanado dataframes

In [ ]:
#merge-join
#concat hace un stak, va creciendo por filas o por columnas(match de forma horizontal)


In [ ]:
df1=pd.DataFrame({'A':['A0','A1','A2','A3'],
 'B':['B0','B1','B2','B3'],
 'C':['C0','C1','C2','C3'],
 'D':['D0','D1','D2','D3']})

df2=pd.DataFrame({'A':['A4','A5','A6','A7'],
 'B':['B4','B5','B6','B7'],
 'C':['C4','C5','C6','C7'],
 'D':['D4','D5','D6','D7']})


In [ ]:
#por defaul lo hace por el axis=0
pd.concat([df1,df2],ignore_index=True)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
#modificamos por el axis=1
pd.concat([df1,df2],axis=1)

A   B   C   D   A   B   C   D
0  A0  B0  C0  D0  A4  B4  C4  D4
1  A1  B1  C1  D1  A5  B5  C5  D5
2  A2  B2  C2  D2  A6  B6  C6  D6
3  A3  B3  C3  D3  A7  B7  C7  D7

In [ ]:
#merge
#axis=1, horizontal
#axis=0, vertical
Izq=pd.DataFrame({'key':['k0','k1','k2','k3'],
 'A':['A0','A1','A2','A3'],
 'B':['B0','B1','B2','B3']})

Der=pd.DataFrame({'key':['k0','k1','k2','k3'],
  'C':['C4','C5','C6','C7'],
 'D':['D4','D5','D6','D7']})

In [ ]:
Izq.merge(Der)

key   A   B   C   D
0  k0  A0  B0  C4  D4
1  k1  A1  B1  C5  D5
2  k2  A2  B2  C6  D6
3  k3  A3  B3  C7  D7

In [ ]:
Izq.merge(Der,on='key')

key   A   B   C   D
0  k0  A0  B0  C4  D4
1  k1  A1  B1  C5  D5
2  k2  A2  B2  C6  D6
3  k3  A3  B3  C7  D7

In [ ]:
Izq=pd.DataFrame({'key':['k0','k1','k2','k3'],
 'A':['A0','A1','A2','A3'],
 'B':['B0','B1','B2','B3']})

Der=pd.DataFrame({'key_2':['k0','k1','k2','k3'],
  'C':['C4','C5','C6','C7'],
 'D':['D4','D5','D6','D7']})

In [ ]:
Izq.merge(Der,left_on='key',right_on='key_2')

key   A   B key_2   C   D
0  k0  A0  B0    k0  C4  D4
1  k1  A1  B1    k1  C5  D5
2  k2  A2  B2    k2  C6  D6
3  k3  A3  B3    k3  C7  D7

In [ ]:
Izq=pd.DataFrame({'key':['k0','k1','k2','k3'],
 'A':['A0','A1','A2','A3'],
 'B':['B0','B1','B2','B3']})

Der=pd.DataFrame({'key_2':['k0','k1','k2',np.nan],
  'C':['C4','C5','C6','C7'],
 'D':['D4','D5','D6','D7']})

In [ ]:
Der

key_2   C   D
0    k0  C4  D4
1    k1  C5  D5
2    k2  C6  D6
3   NaN  C7  D7

In [ ]:
#solo trae la interseccion entre ambos, sin considerar la fila
Izq.merge(Der,left_on='key',right_on='key_2',how='left')

key   A   B key_2    C    D
0  k0  A0  B0    k0   C4   D4
1  k1  A1  B1    k1   C5   D5
2  k2  A2  B2    k2   C6   D6
3  k3  A3  B3   NaN  NaN  NaN

In [ ]:
Izq.merge(Der,left_on='key',right_on='key_2',how='inner')

key   A   B key_2   C   D
0  k0  A0  B0    k0  C4  D4
1  k1  A1  B1    k1  C5  D5
2  k2  A2  B2    k2  C6  D6

In [ ]:
Izq.merge(Der,left_on='key',right_on='key_2',how='right')

key    A    B key_2   C   D
0   k0   A0   B0    k0  C4  D4
1   k1   A1   B1    k1  C5  D5
2   k2   A2   B2    k2  C6  D6
3  NaN  NaN  NaN   NaN  C7  D7

JOIN INDEX_MATCH

In [ ]:
#va directamente a los indices de df
izq=pd.DataFrame({'A':['A0','A1','A2','A3'],
 'B':['B0','B1','B2','B3']},
 index=['k0','k1','k2','k3'])

der=pd.DataFrame({'C':['C4','C5','C6','C7'],
 'D':['D4','D5','D6','D7']},
 index=['k0','k1','k2','k4'])

In [ ]:
izq.join(der,how='outer') #left, right, outer, inner

A    B    C    D
k0   A0   B0   C4   D4
k1   A1   B1   C5   D5
k2   A2   B2   C6   D6
k3   A3   B3  NaN  NaN
k4  NaN  NaN   C7   D7

PIVOT Y MELT

transforma los valores de determinadas columnas o filas en los índices de un nuevo DataFrame, y la intersección de estos es el valor resultante.

In [ ]:
#pivot_table y melt
df_books = pd.read_csv('/content/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv',sep=',',header=0)

In [ ]:
df_books.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [ ]:
#Como resultado, los valores de Author pasan a formar el índice por fila y los valores de Genre pasan a formar parte de
#los índices por columna, y el User Rating se mantiene como valor.
df_books.pivot_table(index='Author',columns='Genre',values='User Rating')

Genre                       Fiction  Non Fiction
Author                                          
Abraham Verghese                4.6          NaN
Adam Gasiewski                  NaN     4.400000
Adam Mansbach                   4.8          NaN
Adir Levy                       4.8          NaN
Admiral William H. McRaven      NaN     4.700000
...                             ...          ...
Walter Isaacson                 NaN     4.566667
William Davis                   NaN     4.400000
William P. Young                4.6          NaN
Wizards RPG Team                4.8          NaN
Zhi Gang Sha                    NaN     4.600000

[248 rows x 2 columns]

En este caso tenemos por cada género, la suma a lo largo de los años. Esto es mucho más interesante, ¿verdad? La mejor noticia es que no solo podemos obtener la suma, también podemos obtener la media, la desviación estándar, el conteo, la varianza, etc. Únicamente con cambiar el parámetro aggfunc que traduce función de agrupamiento.

In [ ]:
df_books.pivot_table(index='Genre',columns='Year', values='User Rating',aggfunc='sum')

Year          2009   2010   2011   2012   2013   2014   2015   2016   2017  \
Genre                                                                        
Fiction      110.2   92.3   97.0   94.4  109.1  134.3   79.1   89.6  113.7   
Non Fiction  119.0  135.6  130.9  132.2  118.6   96.8  153.3  144.3  119.3   

Year          2018   2019  
Genre                      
Fiction       99.5   96.4  
Non Fiction  133.9  140.6

MELT

El método melt toma las columnas del DataFrame y las pasa a filas, con dos nuevas columnas para especificar la antigua columna y el valor que traía.

In [ ]:
df_books[['Name','Genre']].head(5)

Name        Genre
0                      10-Day Green Smoothie Cleanse  Non Fiction
1                                  11/22/63: A Novel      Fiction
2            12 Rules for Life: An Antidote to Chaos  Non Fiction
3                             1984 (Signet Classics)      Fiction
4  5,000 Awesome Facts (About Everything!) (Natio...  Non Fiction

In [ ]:
df_books[['Name','Genre']].head(5).melt()

variable                                              value
0     Name                      10-Day Green Smoothie Cleanse
1     Name                                  11/22/63: A Novel
2     Name            12 Rules for Life: An Antidote to Chaos
3     Name                             1984 (Signet Classics)
4     Name  5,000 Awesome Facts (About Everything!) (Natio...
5    Genre                                        Non Fiction
6    Genre                                            Fiction
7    Genre                                        Non Fiction
8    Genre                                            Fiction
9    Genre                                        Non Fiction

In [ ]:
df_books.melt(id_vars='Year',value_vars='Genre')

Year variable        value
0    2016    Genre  Non Fiction
1    2011    Genre      Fiction
2    2018    Genre  Non Fiction
3    2017    Genre      Fiction
4    2019    Genre  Non Fiction
..    ...      ...          ...
545  2019    Genre      Fiction
546  2016    Genre  Non Fiction
547  2017    Genre  Non Fiction
548  2018    Genre  Non Fiction
549  2019    Genre  Non Fiction

[550 rows x 3 columns]

Hemos conocido pivot y melt, dos herramientas muy útiles para manipular nuestros DataFrames.

APPLY

In [ ]:
#permite aplicar fuciones anuestro dataframe
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

In [ ]:
def two_times(value):
  return value*2

In [ ]:
df_books['User Rating'].apply(two_times)

0      9.4
1      9.2
2      9.4
3      9.4
4      9.6
      ... 
545    9.8
546    9.4
547    9.4
548    9.4
549    9.4
Name: User Rating, Length: 550, dtype: float64

In [ ]:
df_books['Raiting_2']=df_books['User Rating'].apply(lambda x:x*3)

In [ ]:
df_books.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  \
0                  JJ Smith          4.7    17350      8  2016  Non Fiction   
1              Stephen King          4.6     2052     22  2011      Fiction   
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3             George Orwell          4.7    21424      6  2017      Fiction   
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction   

   Raiting_2  
0       14.1  
1       13.8  
2       14.1  
3       14.1  
4       14.4

In [ ]:
df_books['Rating_3']=df_books.apply(lambda x: x['User Rating']*2 if x['Genre']=='Fiction' else x['User Rating'],axis=1)

In [ ]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     Raiting_2  Rating_2  Rating_3  
0         14.1       4.7       4.7  
1         13.8       9.2       9.2  
2         14.1       4.7       4.7  
3         14.1       9.4       9.4  
4         14.4       4.8       4.8  
..         ...       ...       ...  
545       14.7       9.8       9.8  
546       14.1       4.7       4.7  
547       14.1       4.7       4.7  
548       14.1       4.7       4.7  
549       14.1       4.7       4.7  

[550 rows x 10 columns]

In [ ]:
df_books.apply()

TypeError: ignored


pandas.DataFrame.apply — pandas 1.4.1 documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html

In [ ]:
np.array(['hola','2','4','5'],dtype='float64')

ValueError: ignored

In [ ]:
arr = np.array([13, 6, 3, 5, 10])
np.argmax(arr)

0

In [ ]:
df_books.loc[0:10, ['Name', 'Author']]

Name  \
0                       10-Day Green Smoothie Cleanse   
1                                   11/22/63: A Novel   
2             12 Rules for Life: An Antidote to Chaos   
3                              1984 (Signet Classics)   
4   5,000 Awesome Facts (About Everything!) (Natio...   
5       A Dance with Dragons (A Song of Ice and Fire)   
6   A Game of Thrones / A Clash of Kings / A Storm...   
7                      A Gentleman in Moscow: A Novel   
8       A Higher Loyalty: Truth, Lies, and Leadership   
9                           A Man Called Ove: A Novel   
10                          A Man Called Ove: A Novel   

                      Author  
0                   JJ Smith  
1               Stephen King  
2         Jordan B. Peterson  
3              George Orwell  
4   National Geographic Kids  
5        George R. R. Martin  
6        George R. R. Martin  
7                Amor Towles  
8                James Comey  
9            Fredrik Backman  
10           Fredrik Backman

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96